<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Dekoeky.AppBridge</AssemblyTitle>
    <AssemblyName>Dekoeky.AppBridge</AssemblyName>
    <RootNamespace>Dekoeky.AppBridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AppBridge.Tests" />
  </ItemGroup>

</Project>
