<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>dekoeky</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="testfiles\c#\Goodbye.cs" />
    <Compile Remove="testfiles\c#\Greeting.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="testfiles\c#\Goodbye.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="testfiles\c#\Greeting.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VsCode.Cli\VsCode.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="testfiles\csv\cars.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testfiles\csv\people1.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testfiles\csv\people2.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
