<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>dekoeky.VsCode.Cli</AssemblyTitle>
    <AssemblyName>dekoeky.VsCode.Cli</AssemblyName>
    <RootNamespace>dekoeky</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VsCode.Cli.Tests" />
  </ItemGroup>

</Project>
