<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Dekoeky.AppBridge.WinMerge.Tests</AssemblyTitle>
    <AssemblyName>Dekoeky.AppBridge.WinMerge.Tests</AssemblyName>
    <RootNamespace>Dekoeky.AppBridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestData\c#\Goodbye.cs" />
    <Compile Remove="TestData\c#\Greeting.cs" />
    <Compile Remove="TestData\c#\GreetingIdentical.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestData\c#\Goodbye.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="TestData\c#\GreetingIdentical.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="TestData\c#\Greeting.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppBridge.WinMerge\AppBridge.WinMerge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\csv\cars.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData\csv\people1.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData\csv\people2.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
