<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Dekoeky.AppBridge.Windows</AssemblyTitle>
    <AssemblyName>Dekoeky.AppBridge.Windows</AssemblyName>
    <RootNamespace>Dekoeky.AppBridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dekoeky.AppBridge.Windows.Tests" />
  </ItemGroup>

</Project>
