<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Dekoeky.AppBridge.WinMerge</AssemblyTitle>
    <AssemblyName>Dekoeky.AppBridge.WinMerge</AssemblyName>
    <RootNamespace>Dekoeky.AppBridge</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dekoeky.AppBridge.WinMerge.Tests" />
  </ItemGroup>
  
</Project>
